spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:p6spy:mysql://180.76.174.95:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
#    password: 123456
  freemarker:
    cache: false
    suffix: .ftl
  redis:
    host: localhost
    port: 6379
    password:
  data:
## es-v6.8.8
## webUI: http://192.168.88.61:9100
    elasticsearch:
      cluster-name: my-es
      cluster-nodes: 192.168.88.61:9300,192.168.88.62:9300,192.168.88.63:9300
      repositories:
        enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 15672
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
file:
  upload:
    dir: ${user.dir}/upload
